### ISSUE TITLE
issue on code style

### ISSUE THREAD

**Issue by yiliqian** [wilkija/python-intermediate-inflammation#7]
https://github.com/wilkija/python-intermediate-inflammation/blob/76df9842898bd8fefda293a85adaf0c270795fdb/tests/test_models.py

Line 144: It would be nice to have two blank lines between functions.

**Comment by wilkija** [comment]
Thank you for the suggestion @yiliqian. I will give this some more thought. Though, a space at line 144 may not be necessary because the code above is the parameters for the test function below it.
